apiVersion: agents.platform/v1
kind: Skill
metadata:
  labels:
    app.kubernetes.io/name: agent-platform
    app.kubernetes.io/managed-by: kustomize
  name: skill-sample
spec:
  # TODO(user): Add fields here
